import Head from "next/head";
import { Hero, Layout, Links, PLink, styles } from "@/components";
import { Interested } from "@/components/landing-page";
import { cards, ourObjs } from "@/constants/about";
import { AiFillLike } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>AANI | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          <Hero img={"aboutHero"} title={"About AANI"}></Hero>
          <section className="">
            <div className="flex justify-center items-center mb-4 md:mb-12">
              <PLink
                styles="text-gray mr-3 text-[17px] cursor-pointer"
                href="/"
                text="Home"
              />
              /
              <h5 className="text-paleBlue border-b ml-3 text-[17px]">
                ABOUT US
              </h5>
            </div>
            <div className="flex flex-col md:flex-row sm:px-10 px-4  sm:pb-20 pb-4">
              <ul className="list-none flex md:flex-col mb-10">
                <Links />
              </ul>
              <div className={`${styles.paddingX}`}>
                <div
                  className={`flex grow justify-around flex-wrap md:mb-20 mb-10 `}
                >
                  {cards.map((card, idx) => (
                    <div
                      key={idx}
                      className="w-[300px] sm:w-[360px] shadow-lg p-3 bg-white border border-darkGray mb-14"
                    >
                      <h3 className="font-bold text-primary text-[25px] mb-3">
                        {card?.title}
                      </h3>
                      {card.content && (
                        <p className=" text-[18px]  lg:text-[25px] text-gray font-normal">
                          {card.content}
                        </p>
                      )}
                      {/* {card?.list && (
                        <ul>
                          {card?.list.map((item, idx) => (
                            <li
                              key={idx}
                              className=" text-[18px]  lg:text-[25px] text-gray font-normal"
                            >
                              {item}
                            </li>
                          ))}
                        </ul>
                      )} */}
                    </div>
                  ))}
                </div>
                <div className="my-3 md:my-10">
                  <h3 className="font-bold text-primary  text-[25px]  lg:text-[36px] mb-5">
                  The Genesis of the Association
                  </h3>
                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                  In his lecture at the 30th anniversary of the Institute Chief Olusegun Obasanjo, GCFR, founder of NIPSS and former President of the Federal Republic of Nigeria described the Alumni Association of the National Institute (AANI) as {`"an unplanned outcome of a purposeful action"`}. The Association was inaugurated twice.
                  </p>
                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                  The first inauguration was done by the pioneer Director- General, late Major-General TB Ogundeko, in March 1980 during the graduation ceremony of Senior Executive Course 1, 1979, in Jos. The second inauguration took place in Kuru on Saturday, 28 February, 1981, under the distinguished chairmanship of late Alhaji Ahmed Talib, a key member of the very first Board of Governors. The intention was, and still remains: {`"to provide all former students with a formal and continuing opportunity to relate to the ideas and activities of the Institute".`}
                  </p>
                </div>

                <div className="my-3 md:my-10">
                  <h3 className="font-bold text-primary  text-[25px]  lg:text-[36px] mb-5">
                  Administrative and other organs of the Association
                  </h3>
                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                  The organs of the Association comprise:
                  </p>
                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                  The Annual General Meeting (AGM), The National Executive Committee (NEC), Standing Committees, and Chapter Executive Committees. At the beginning, the Association operated in six zones, namely: Kaduna, Enugu, Ibadan, Lagos, Bauchi, and Abuja. However, in order to achieve better and more effective coordination, the zones were increased to ten - Abuja, Bauchi, Benin, Borno, Enugu, Ibadan, Kaduna, Lagos, Port Harcourt, and Sokoto.
                  </p>

                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                  The new configuration was based on contiguity of states, convenience of contact, and programming rather than on membership strength. Each Zone is headed by a Chairman, who is automatically a member of the National Executive Committee. The zones engage in activities which are designed to promote the gains of the Senior Executive Course, and the Kuru dream.
                  </p>

                  
                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                  The contribution of the zones to national development is through seminars, symposia, and similar activities, where issues strategic to the nations progress are discussed. From ten zones in 2003, the Association now has twenty-seven Chapters functioning in twenty-seven states of the federation. The Association elects an executive committee every two years to run its affairs. The National Executive Committee (NEC) comprises the President and these other members, namely:
                  </p>
                        <ol>
                          <li>Vice-President</li>
                          <li>Secretary-General</li>
                          <li>Assistant Secretary-General</li>
                          <li>Financial Secretary</li>
                          <li>Treasurer</li>
                        </ol>
                </div>
                <div className="">
                  <h3 className="font-bold text-primary   text-[25px]  lg:text-[36px] mb-5">
                  Purpose of setting up AANI by the founding fathers
                  </h3>
                  {ourObjs.map((obj, idx) => (
                    <div key={idx} className="flex w-full mb-3 md:mb-6">
                      <div className="pr-1">
                        <AiFillLike className="text-primary  text-[25px]  lg:text-[36px]" />
                      </div>
                      <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                        {obj}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>
          <div
            className={`bg-[url(/aboutMem.jpg)] bg-no-repeat bg-cover flex justify-center items-center p-4 md:p-20 z-20 relative`}
          >
            <Interested />
          </div>
        </Layout>
      </main>
    </>
  );
}
