import Head from "next/head";
import { LayoutFn } from "@/components/Layout";
import { Hero, styles } from "@/components";
import Image from "next/image";
const a= [
  494, 495, 599, 497, 498, 499, 500,523,
  524, 525,574, 575
]
export default function Gallery() {
  return (
    <>
      <Head>
        <title>AANI | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <LayoutFn>
          <Hero img={`aani/IMG-20220901-WA0599`} title={'Gallery'}></Hero>
          <div className={`mb-10 md:mb-20 ${styles.paddingX}`}>
            <div className="grid xl:grid-cols-4 lg:grid-cols-3 gap-4 sm:grid-cols-2">
              {a.map((a, idx) => (
                <img
                src={`/aani/IMG-20220901-WA0${a}.jpg`}
                  alt={""}
                  key={a}
                  style={{'width':'100%',height:'100%'}}
                  className="object-cover"
                />
              ))}
            </div>
          </div>
        </LayoutFn>
      </main>
    </>
  );
}
